[package]
name = "rustymines-jar3n"
version = "1.1.1"
edition = "2024"
authors = ["James Englander jamreng@proton.me"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jar3n/rustymines"
repository = "https://github.com/jar3n/rustymines"
keywords = ["game", "minesweeper", "tui", "terminal"]
categories = ["games"]
description = "Minesweeper in the terminal"
exclude = [".gitignore"]

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
rand = "0.10.2"
ratatui = "0.30.2"
strum = "0.28.0"
